services:
    postgres:
        image: postgres:16.4-alpine
        container_name: postgres
        restart: always
        env_file: .env
        ports:
          - "5432:5432"
        expose:
          - 5432
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/dbfiles
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    tg_bot:
      build:
          dockerfile: Dockerfile
      env_file: .env
      volumes:
        - .:/app
      depends_on:
        - postgres

    redis:
      image: redis:7-alpine
      restart: always
      env_file: .env
      ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
      expose:
        - "${REDIS_PORT}"
      volumes:
        - redis-data:/data


volumes:
  postgres-data:
  redis-data: